config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#welcome'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :reviews
  resources :baby_foods do
    resources :reviews, only:[:new, :index]
  end
  resources :categories
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby_food.rb
class BabyFood < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews

  accepts_nested_attributes_for :category

  validates :flavor, presence: true
  validate :no_duplicates

  def self.alpha
    order(:flavor)
  end

  # def category_attributes(attributes)
  #   self.category = Category.find_or_create_by(attribute) if !attributes['name'].empty?
  #   self.category
  # end

  def no_duplicates
    if BabyFood.find_by(flavor: flavor, category_id: category_id)
      errors.add(:flavor, 'has already been added for that category')
    end
  end

  def flavor_and_category
    "#{flavor} - #{category.name}"
  end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :baby_foods

    validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :baby_food

  validates :stars, numericality: true
  validates :title, presence: true

  validates :baby_food, uniqueness: {scope: :user, message: "has already been reviewed by you."}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :reviewed_baby_foods, through: :reviews, source: :baby_food

    has_many :baby_foods

    has_secure_password

    validates :username, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private
    
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    end
end

app/controllers/baby_foods_controller.rb
class BabyFoodsController < ApplicationController
    def new
        @baby_food = BabyFood.new
        @baby_food.build_category
    end

    def create
        @baby_food = BabyFood.new(baby_food_params)
        @baby_food.user_id = session[:user_id]

        if @baby_food.save
            redirect_to baby_food_path(@baby_food)
        else
            @baby_food.build_user
            render :new
        end
    end

    def index
        @baby_foods = BabyFood.all
    end

    def show
        @baby_food = BabyFood.find_by_id(params[:id])
    end

    private

    def baby_food_params
        params.require(:baby_food).permit(:flavor, :description, :category_id, category_attributes: [:name])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        if @baby_food = BabyFood.find_by_id(params[:baby_food_id])
            @review = @baby_food.reviews.build
        else
            @review = Review.new
        end
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to review_path(@review)
        else
            render :new
        end
    end

    def show
        @review = Review.find_by_id(params[:id])
    end

    def index
        if @baby_food = BabyFood.find_by_id(params[:baby_food_id])
            @reviews = @baby_food.reviews
        else
            @reviews = Review.all
        end
    end

    private

    def review_params
        params.require(:review).permit(:baby_food_id, :stars, :title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome
    end

    def destroy
        session.clear
        redirect_to '/'
    end

    def new
    end

    def create
        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:message] = "Invalid credentials. Please try again."
            redirect_to login_path
        end
    end

    def omniauth
        @user = User.create_from_omniauth(auth)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to '/'
        end
    end

    private

    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find_by_id(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def nav_bar
        if logged_in?
            render partial: 'layouts/loggedin_nav'
        end
    end
end

app/helpers/baby_foods_helper.rb
module BabyFoodsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baby_foods/index.html.erb
<h1>All of your baby's foods!</h1>

<% @baby_foods.each do |bf| %>
    <h3><%= bf.flavor %> - <%= bf.category.name %></h3>
<div>
    <p><%= bf.description %></p>
</div>
<%= link_to "Write a Review", new_baby_food_review_path(bf.id) %>
<% end %>

app/views/baby_foods/new.html.erb
<h1>Add a new baby food!</h1>

<%= render partial: 'layouts/errors', locals: {object: @baby_food} %>

<%= form_for(@baby_food) do |f| %>
    <div>
        <%= f.label :flavor %>
        <%= f.text_field :flavor %><br><br>
    </div>

    <div>
        <%= f.label :description %>
        <%= f.text_field :description %><br><br>
    </div>

    Select an existing Category:
    <div>
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: 'Select One' %><br><br>
    </div>

    Create a new Category:
    <div>
        <%= f.fields_for :category do |c| %>
            <%= c.label :name %>
            <%= c.text_field :name %>
        <% end %>
    </div><br>

    <%= f.submit %>
<% end %>

app/views/baby_foods/show.html.erb
<h1><%= @baby_food.flavor %></h1>

<div>
    <p><%= @baby_food.description %></p>
</div>

app/views/categories/index.html.erb
<h1>All Categories:</h1>

<ol>
    <% @categories.each do |c|%>
        <li><%= c.name %></li>
    <% end %>
</ol>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2 style="color: red;">
      <%= pluralize(object.errors.count, "error") %>
      prohibited this from being saved:
    </h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li style="color: red;"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin_nav.html.erb
<strong><%= link_to "Home", user_path(current_user)%></strong> /
<%= link_to "Add a Baby Food", new_baby_food_path %> /
<%= link_to "All your Baby's Foods", baby_foods_path %> /
<%= link_to "Add a Review", new_review_path %> /
<%= link_to "All Reviews", reviews_path %> /
<%= link_to "All Categories", categories_path %> /
<strong><%= link_to "Log Out", logout_path, method: :delete %></strong> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baby Food Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <%= nav_bar %>
  </div>

  <body>
    <center><u><h1>Baby Food Tracker</h1></u></center>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<h1>All Reviews</h1>

<% @reviews.each do |r| %>
    <ul>
        <li><%= r.baby_food.flavor %>: <%= r.title %> - <%= r.stars %></li>
    </ul>
<% end %>

app/views/reviews/new.html.erb
<h1>Write a Review for "<%= @review.baby_food %>"!</h1>

<%= render partial: 'layouts/errors', locals: {object: @review} %>

<%= form_for(@review) do |f| %>
    <% if params[:baby_food_id]%>
        <%= f.hidden_field :baby_food_id %>
    <% else %>
        <div>
            <%= f.label :baby_food_id, 'Select a Baby Food' %>
            <%= f.collection_select :baby_food_id, BabyFood.alpha, :id, :flavor_and_category, include_blank: true %>
        </div><br>
    <% end %>
        <div>
            <%= f.label :stars %>
            <%= f.number_field :stars, min:1, max:5 %><br><br>
        </div>

        <div>
            <%= f.label :title %>
            <%= f.text_field :title %><br><br>
        </div>

        <div>
            <%= f.label :content %>
            <%= f.text_area :content, rows: "4", cols:"50" %><br><br>
        </div>

        <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h1><%= @review.title %> - <%= @review.stars %></h1>

app/views/users/new.html.erb
<h1>Sign Up.</h1>

<%= render partial: 'layouts/errors', locals: {object: @user} %>

<%= form_for(:user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %><br><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br><br>

    <%= f.submit "Sign Up" %>
<% end %>

<h3>Already have an account? Please <%= link_to "Log In.", login_path %></h3>

app/views/users/show.html.erb
<p style="color: red;">
    <%= flash[:message] if flash[:message] %>
</p>

<h1>Welcome <%= @user.username %> !!!</h1>